# Generated by Django 5.1 on 2024-09-19 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlgi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIngresos',
            fields=[
                ('id_tipo_ingresos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tipo_ingresos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='controlgi.tipoingresos'),
        ),
    ]
