# Generated by Django 5.1 on 2024-09-19 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlgi', '0002_tipoingresos_ingresos_tipo_ingresos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='tipo_ingresos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='controlgi.tipoingresos'),
        ),
    ]
