# Generated by Django 5.1 on 2024-09-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='direccion',
            new_name='correo',
        ),
    ]
